# Build: from parent directory
# docker build -t api -f .\code\deployment\api\Dockerfile .

FROM python:3.10

# set a directory for the app
WORKDIR /usr/src/app

COPY ./requirements.txt .
# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# copy all the files to the container
COPY ./code/deployment/api/ .
COPY ./code/models/model_cnn.py .
COPY ./models/mnist_cnn.pt .

# define the port number the container should expose
EXPOSE 8000

# run the command
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]